name: Vite Bootstrap CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CI: true
  NODE_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Uses Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run cy:i
          npx browserslist@latest --update-db

      - name: EsLint
        run: pnpm run lint

      - name: Type validation
        run: pnpm run type

      - name: Test
        run: pnpm run test:ci --coverage

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      # CYPRESS
      - name: Start Nginx
        run: |
          export ABSOLUTE_PATH=`pwd`
          docker run -it --rm -d -p 3433:80 --name web -v $ABSOLUTE_PATH/dist:/usr/share/nginx/html nginx

      - name: Setup and Run Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_FORCE_NEW_TOKEN: false
        with:
          wait-on: "http://localhost:3433"
          wait-on-timeout: 60
          spec: |
            cypress/e2e/test.cy.ts
          install: false
          browser: chrome

      - name: Cypress Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Cypress Artifacts
          path: |
            cypress/screenshots
            cypress/videos
